export interface Match {
    id: string,
    userId: string,
    homeTeam: string,
    awayTeam: string,
    venue: string,
    date: Date,
    motm: string,
    ongoing: boolean,
    format: string,
    result: string,
    winner: string,
    homeTeamEmblem: File | null,
    awayTeamEmblem: File | null,
}