import { Player } from "../types/player";

export const squads : Player[] = [
    {
        firstname: "Moeen",
        surname: "Ali",
        dob: "18/06/1987",
        nationalTeam: "England",
        icon: "https://resources.ecb.co.uk/player-photos/test/150x150/1735.png",
        position: "All-Rounder",
    },
    {
        firstname: 'Ben',
        surname: 'Stokes',
        dob: '04/06/1991',
        nationalTeam: 'England',
        icon: 'https://resources.ecb.co.uk/player-photos/test/150x150/1154.png',
        position: 'All-Rounder',
    },
    {
        firstname: 'Joe',
        surname: 'Root',
        dob: '30/12/1990',
        nationalTeam: 'England',
        icon: 'https://resources.ecb.co.uk/player-photos/test/150x150/887.png',
        position: 'Batsman',
    },
    {
        firstname: 'Jonny',
        surname: 'Bairstow',
        dob: '26/09/1989',
        nationalTeam: 'England',
        icon: 'https://resources.ecb.co.uk/player-photos/test/480x480/506.png',
        position: 'Batsman',
    },
    {
        firstname: 'Ollie',
        surname: 'Pope',
        dob: '02/01/1998',
        nationalTeam: 'England',
        icon: 'https://resources.ecb.co.uk/player-photos/test/480x480/3636.png',
        position: 'Batsman',
    },
    {
        firstname: 'Zak',
        surname: 'Crawley',
        dob: '03/04/1998',
        nationalTeam: 'England',
        icon: 'Zak Crawley https://resources.ecb.co.uk/player-photos/test/480x480/4332.png',
        position: 'Batsman',
    },
    {
        firstname: 'Harry',
        surname: 'Brook',
        dob: '24/09/1998',
        nationalTeam: 'England',
        icon: 'https://resources.ecb.co.uk/player-photos/test/480x480/3375.png',
        position: 'Batsman',
    },
    {
        firstname: 'James',
        surname: 'Anderson',
        dob: '30/07/1982',
        nationalTeam: 'England',
        icon: 'https://resources.ecb.co.uk/player-photos/test/480x480/900.png',
        position: 'Bowler',
    },
    {
        firstname: 'Stuart',
        surname: 'Broad',
        dob: '24/06/1986',
        nationalTeam: 'England',
        icon: 'https://resources.ecb.co.uk/player-photos/test/480x480/192.png',
        position: 'Bowler',
    },
    {
        firstname: 'Chris',
        surname: 'Woakes',
        dob: '02/03/1989',
        nationalTeam: 'England',
        icon: 'https://resources.ecb.co.uk/player-photos/test/480x480/967.png',
        position: 'Bowler',
    },
    {
        firstname: 'Mark',
        surname: 'Wood',
        dob: '11/01/1990',
        nationalTeam: 'England',
        icon: 'https://resources.ecb.co.uk/player-photos/test/480x480/2749.png',
        position: 'Bowler',
    },
    {
        firstname: 'Rehan',
        surname: 'Ahmed',
        dob: '01/01/1990',
        nationalTeam: 'England',
        icon: 'https://resources.ecb.co.uk/player-photos/test/480x480/photo-missing.png',
        position: 'Bowler',
    },
    {
        firstname: 'Jack',
        surname: 'Leach',
        dob: '22/06/1991',
        nationalTeam: 'England',
        icon: 'https://resources.ecb.co.uk/player-photos/test/480x480/3363.png',
        position: 'Bowler',
    },
    {
        firstname: 'Matthew',
        surname: 'Potts',
        dob: '28/11/1998',
        nationalTeam: 'England',
        icon: 'https://resources.ecb.co.uk/player-photos/test/480x480/4340.png',
        position: 'Bowler',
    },
    
    {
        firstname: 'Ben',
        surname: 'Duckett',
        dob: '17/10/1994',
        nationalTeam: 'England',
        icon: 'https://resources.ecb.co.uk/player-photos/test/480x480/1542.png',
        position: 'Batsman',
    },
    {
        firstname: 'Josh',
        surname: 'Tongue',
        dob: '05/03/1998',
        nationalTeam: 'England',
        icon: 'https://resources.ecb.co.uk/player-photos/test/480x480/3592.png',
        position: 'Bowler',
    },
    {
        firstname: 'Ollie',
        surname: 'Robinson',
        dob: '01/12/1993',
        nationalTeam: 'England',
        icon: 'https://resources.ecb.co.uk/player-photos/test/480x480/4434.png',
        position: 'Bowler',
    },
    {
        firstname: 'Usman',
        surname: 'Khawaja',
        dob: '18/12/1986',
        nationalTeam: 'Australia',
        icon: 'https://resources.ecb.co.uk/player-photos/test/150x150/948.png',
        position: 'Batsman',
    },
    {
        firstname: 'Steve',
        surname: 'Smith',
        dob: '02/06/1989',
        nationalTeam: 'Australia',
        icon: 'https://resources.ecb.co.uk/player-photos/test/150x150/271.png',
        position: 'Batsman',
    },
    {
        firstname: 'David',
        surname: 'Warner',
        dob: '27/10/1986',
        nationalTeam: 'Australia',
        icon: 'https://resources.ecb.co.uk/player-photos/test/150x150/170.png',
        position: 'Batsman',
    },
    {
        firstname: 'Marnus',
        surname: 'Labuschagne',
        dob: '22/06/1994',
        nationalTeam: 'Australia',
        icon: 'https://resources.ecb.co.uk/player-photos/test/150x150/4029.png',
        position: 'Batsman',
    },
    {
        firstname: 'Travis',
        surname: 'Head',
        dob: '29/12/1993',
        nationalTeam: 'Australia',
        icon: 'https://resources.ecb.co.uk/player-photos/test/150x150/1020.png',
        position: 'Batsman',
    },
    {
        firstname: 'Pat',
        surname: 'Cummins',
        dob: '08/05/1993',
        nationalTeam: 'Australia',
        icon: 'https://resources.ecb.co.uk/player-photos/test/150x150/488.png',
        position: 'Bowler',
    },
    {
        firstname: 'Mitchell',
        surname: 'Starc',
        dob: '30/01/1990',
        nationalTeam: 'Australia',
        icon: 'https://resources.ecb.co.uk/player-photos/test/150x150/490.png',
        position: 'Bowler',
    },
    {
        firstname: 'Josh',
        surname: 'Hazlewood',
        dob: '08/01/1991',
        nationalTeam: 'Australia',
        icon: 'https://resources.ecb.co.uk/player-photos/test/150x150/857.png',
        position: 'Bowler',
    },
    {
        firstname: 'Nathan',
        surname: 'Lyon',
        dob: '20/11/1987',
        nationalTeam: 'Australia',
        icon: 'https://resources.ecb.co.uk/player-photos/test/150x150/797.png',
        position: 'Bowler',
    },
    {
        firstname: 'Alex',
        surname: 'Carey',
        dob: '27/08/1991',
        nationalTeam: 'Australia',
        icon: 'https://resources.ecb.co.uk/player-photos/test/150x150/3882.png',
        position: 'Bowler',
    },
    {
        firstname: 'Scott',
        surname: 'Boland',
        dob: '11/04/1989',
        nationalTeam: 'Australia',
        icon: 'https://resources.ecb.co.uk/player-photos/test/150x150/1475.png',
        position: 'Bowler',
    },
    {
        firstname: 'Cameron',
        surname: 'Green',
        dob: '03/06/1999',
        nationalTeam: 'Australia',
        icon: 'https://resources.ecb.co.uk/player-photos/test/150x150/4093.png',
        position: 'Bowler',
    },
]
